app/models.py
"""Stories Database schema."""

import datetime
import flask_sqlalchemy
import werkzeug.security
import flask_login
import app


class User(flask_login.UserMixin, app.db.Model):
    """User table."""

    _id = app.db.Column('id', app.db.Integer, primary_key=True)
    username = app.db.Column(app.db.String(20), unique=True)
    password_hash = app.db.Column(app.db.String(128))

    def __repr__(self):
        return "<User: {0}>".format(self.username)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        """Hashing password"""
        self.password_hash = werkzeug.security.generate_password_hash(password)

    def verify_password(self, password):
        return werkzeug.security.check_password_hash(
            self.password_hash, password)

    def get_id(self):
        return str(self._id)


class Story(app.db.Model):
    """Story table."""

    _id = app.db.Column('id', app.db.Integer, primary_key=True)
    title = app.db.Column(app.db.String(200))
    post = app.db.Column(app.db.Text())
    timestamp = app.db.Column(app.db.DateTime, default=datetime.datetime.utcnow)


@app.login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.get(int(user_id))
    except:
        return None

app/stories/forms.py
"""Story forms"""

from . import fields

import flask_wtf
import wtforms
import wtforms.validators as form_val


class StoryForm(flask_wtf.FlaskForm):
    """Story form from flask_wtf.FlaskForm."""

    title = wtforms.StringField(
        fields.title, validators=[form_val.Required()])
    post = wtforms.TextAreaField(
        fields.post, validators=[form_val.Required()])
    submit = wtforms.SubmitField(fields.submit)


class EditStoryForm(StoryForm):
    """Extend StoryForm to change submit button text"""

    submit = wtforms.SubmitField(fields.edit)

app/__init__.py
from config import config

import flask
import flask_bootstrap
import flask_sqlalchemy
import flask_login
import flask_wtf.csrf


login_manager = flask_login.LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = flask_bootstrap.Bootstrap()
db = flask_sqlalchemy.SQLAlchemy()
csrf = flask_wtf.csrf.CSRFProtect()


def create_app(config_name):
    app = flask.Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)

    import app.main as main_blueprint
    app.register_blueprint(main_blueprint.main)

    import app.stories as stories_blueprint
    app.register_blueprint(stories_blueprint.stories)

    import app.auth as auth_blueprint
    app.register_blueprint(auth_blueprint.auth)

    return app

app/main/__init__.py
"""Initializer."""

import flask


main = flask.Blueprint('main', __name__)


import app.main.views

app/main/views.py
"""Main Views."""

from . import main
import app.models

import sqlalchemy.sql.expression as expression
import flask
import json
import random


@main.route('/')
def home():
    """Get a story"""

    if flask.request.args.get('story'):
        story = app.models.Story.query.get_or_404(
            flask.request.args.get('story'))
    else:
        story = app.models.Story.query.order_by(
            expression.func.random()).first()
    return flask.render_template("home.html", story=story)


@main.route('/quote', methods=['POST'])
def quote():
    """Get a new story """

    story = app.models.Story.query.order_by(
        expression.func.random()).first()
    return json.dumps(story.post)

app/stories/__init__.py
"""Initializer."""

import flask


stories = flask.Blueprint('stories', __name__)


import app.stories.views

app/stories/views.py
"""Stories module"""

from . import stories
from .. import db
import app.stories.forms
import app.models


import flask
import flask_login


@stories.route('/story', methods=['GET', 'POST'])
@flask_login.login_required
def make_story():
    """Generate a view with a form to publish a story."""

    form = app.stories.forms.StoryForm()
    if flask.request.method == 'POST' and form.validate_on_submit():
        story = app.models.Story()
        story.title = form.title.data
        story.post = form.post.data
        app.db.session.add(story)
        app.db.session.commit()
        return flask.redirect(flask.url_for('stories.stories'))
    return flask.render_template("form_template.html", form=form, title="edit Story")


@stories.route('/story/edit/<int:story_id>', methods=['GET', 'POST'])
@flask_login.login_required
def edit_story(story_id):
    """Get the story id as argument and return a view
    with a form to publish or update a story."""

    story = app.models.Story.query.filter_by(
        _id=story_id).first_or_404()
    form = app.stories.forms.EditStoryForm(obj=story)
    form.populate_obj(story)
    if flask.request.method == 'POST' and form.validate_on_submit():
        db.session.add(story)
        db.session.commit()
        return flask.redirect(flask.url_for('stories.stories'))
    return flask.render_template("form_template.html", form=form, title="edit Story")


@stories.route('/story/delete/<int:story_id>', methods=['POST'])
@flask_login.login_required
def delete_story(story_id):
    """Delete story"""

    if flask.request.method == 'POST':
        story = app.models.Story.query.filter_by(
            _id=story_id).first_or_404()
        db.session.delete(story)
        db.session.commit()
    return flask.redirect(flask.url_for('stories.stories'))


@stories.route('/stories')
@flask_login.login_required
def stories():
    """Get all published stories"""

    stories = app.models.Story.query.all()
    return flask.render_template("stories.html", title="Stories", stories=stories)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/google.html" as google %}

{% block metas %}
{{super()}}
  <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}

{% block styles %}
{{super()}}
  <link href="{{url_for('static', filename='style.css')}}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Holtwood+One+SC" rel="stylesheet">

{% endblock %}

{% block navbar%}

<!--[if lt IE 8]>
     <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
 <![endif]-->

{% if current_user.is_authenticated %}
<div class="container-fluid">

  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{url_for('main.home')}}">A Western Stories</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <li> <a href="{{url_for('stories.stories')}}">Storie</a></li>
          <li> <a href="{{url_for('stories.make_story')}}">Nuova Storia</a></li>
          <li> <a href="{{url_for('auth.logout')}}">Logout</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>
{%endif%}

{% endblock %}

{% block content %}

{% block content_page %}{% endblock %}

{% endblock %}

{% block scripts %}
{{super()}}
    <script src="{{url_for('static', filename='main.js')}}"></script>
     {{google.uanalytics('UA-98895588-1')}}
{% endblock %}

app/templates/form_template.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}A Western Story - Login{% endblock %}

{% block content_page %}
  <div class="container container-story">
    <div class="col-md-8 col-md-offset-1 title">
      <h1>A Western Story - {{title}}</h1>
    </div>
    <div class="col-md-6 col-md-offset-3 story">
      {{ wtf.quick_form(form) }}
    </div>
  </div>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}A western Stories{% endblock %}

{% block metas %}
{{super()}}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- Facebook meta -->
  <meta property="og:locale" content="it_IT" />
  <meta property="og:url" content="{{url_for('main.home', _external=True)}}" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="A Western Stories" />
  <meta property="og:site_name" content="A Western Stories" />

  <!-- Twitter -->
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Western Stories" />
{% endblock %}


{% block content_page %}
  <div class="container container-story">
    <div class="col-md-6 col-md-offset-1 title">
      <h1>A Western Story</h1>
    </div>
    <div class="col-md-8 col-md-offset-2 story">
      <p>{{story.post}}</p>
      <div class="loader"></div>
      <button type="button" class="btn btn-default" name="button">Leggi una nuova storia</button>
    </div>
  </div>

{% endblock %}

app/templates/stories.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}


{% block content_page %}
  <div class="container container-story">
    <div class="col-md-6 col-md-offset-1 title">
      <h1>A Western Story - {{title}}</h1>
    </div>
    <div class="col-md-8 col-md-offset-2 story">
        <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Elimina</th>
      </tr>
    </thead>

    <tbody>
      {% for story in stories %}
      <tr>
        <td><a href="{{url_for('stories.edit_story',story_id=story._id)}}">{{story.title}}</a></td>
        <td>
          <form action="{{url_for('stories.delete_story', story_id=story._id)}}" method="POST">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <button class="btn btn-warning" name="story_id">X</button>
          </form>
        </td>
      </tr>
       {% endfor %}
    </tbody>

  </table>

    </div>
  </div>

{% endblock %}